"""Generates the Net // Works Speed, VPN and Wi-Fi cards (shared frame and styles).
Run from anywhere; writes into the skin folders next to @Resources."""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]


def frame(name, info, title, hint, w, h, extra_rainmeter="", measures=""):
    r = w - 18
    return f"""; Net // Works {title} card. Generated by @Resources\\Tools\\generate_net_cards.py
[Rainmeter]
Update=1000
AccurateText=1
DynamicWindowSize=0
{extra_rainmeter}
[Metadata]
Name=Net // Works {name}
Author=ringmast4r
Information={info}
Version=1.0
License=Creative Commons BY-NC-SA 4.0

[Variables]
; Theme is toggled by the button in the top-right corner.
Theme=dark
@Include=#@#Themes\\SinCity-#Theme#.inc
fMono=Courier New
{measures.split('@@VARS@@')[0] if '@@VARS@@' in measures else ''}
; ================= styles
[sCap]
FontFace=#fMono#
FontSize=7
StringStyle=Bold
StringCase=Upper
FontColor=#cMid#
AntiAlias=1

[sHead]
FontFace=#fMono#
FontSize=7
StringStyle=Bold
StringCase=Upper
FontColor=#cBg#
AntiAlias=1

[sCell]
FontFace=#fMono#
FontSize=8
StringStyle=Bold
FontColor=#cFg#
AntiAlias=1
ClipString=1

[sBtn]
FontFace=#fMono#
FontSize=7
StringStyle=Bold
StringAlign=Right
FontColor=#cFg#
SolidColor=#cTrack#
Padding=6,3,6,3
AntiAlias=1
MouseActionCursorName=Hand
{measures.split('@@VARS@@')[1] if '@@VARS@@' in measures else measures}
; ================= card
[MCard]
Meter=Shape
Shape=Rectangle 1.5,1.5,{w-3},{h-3} | Fill Color #cBg# | StrokeWidth 3 | Stroke Color #cFg#
Shape2=Rectangle 18,38,{w-36},3 | Fill Color #cFg# | StrokeWidth 0
Shape3=Rectangle 18,{h-32},{w-36},2 | Fill Color #cFg# | StrokeWidth 0

[MTitle]
Meter=String
FontFace=#fMono#
FontSize=11
StringStyle=Bold
StringCase=Upper
FontColor=#cFg#
AntiAlias=1
X=18
Y=15
Text={title}

[MHint]
Meter=String
MeterStyle=sCap
X={18 + 13 * len(title) + 14}
Y=18
Text={hint}

[MToggle]
Meter=String
MeterStyle=sBtn
X={r - 6}
Y=16
Text=#ToggleLabel#
LeftMouseUpAction=[!WriteKeyValue Variables Theme #ToggleTo#][!Refresh]
ToolTipText=Switch to #ToggleTo# mode

[MFoot]
Meter=String
MeterStyle=sCap
StringCase=None
X=18
Y={h-22}
Text=starting...
"""


def runcommand(script, finish="Parse()"):
    return f"""
; ================= measures
[mRun]
Measure=Plugin
Plugin=RunCommand
Program=powershell.exe
Parameter=-NoProfile -ExecutionPolicy Bypass -File "#@#Scripts\\{script}"
State=Hide
OutputType=UTF8
Timeout=20000
FinishAction=[!CommandMeasure mScript "{finish}"]
"""


def script(lua):
    return f"""
[mScript]
Measure=Script
ScriptFile=#@#Scripts\\{lua}
"""


def table_rows(rows, y0, w, cols, row_h=20, prefix=""):
    """rows: list of (meter_base, label); cols: list of (suffix, x, align, default)."""
    s = ""
    for i, (base, label) in enumerate(rows):
        y = y0 + i * row_h
        if i % 2 == 1:
            s += f"""
[{base}Bg]
Meter=Image
X=18
Y={y}
W={w-36}
H={row_h}
SolidColor=#cAlt#
"""
        for suffix, x, align, default, style in cols:
            text = label if default == "@label" else default
            s += f"""
[{base}{suffix}]
Meter=String
MeterStyle={style}
X={x}
Y={y + (6 if style == 'sCap' else 4)}
{"StringAlign=Right" if align == "R" else ""}
W={170 if suffix in ('Name', 'State') else 230}
H=14
Text={text}
"""
    return s


# ======================================================================= SPEED
W, H = 440, 236
spd = frame("Speed", "Live download and upload speed on the best-route adapter, with a ~7 minute graph, peaks and data used.",
            "Speed", "// live traffic", W, H,
            measures="""
; ================= measures
[mDown]
Measure=NetIn
Interface=Best

[mUp]
Measure=NetOut
Interface=Best
""" + script("Speed.lua"))
for i, (key, cap) in enumerate([("Down", "Download"), ("Up", "Upload")]):
    x0 = 18 + i * 206
    spd += f"""
[{key}Box]
Meter=Shape
Shape=Rectangle {x0+1},51,{196},{64} | Fill Color #cBg# | StrokeWidth 2 | Stroke Color #cFg#

[{key}Cap]
Meter=String
MeterStyle=sCap
X={x0+10}
Y=57
Text={cap}

[{key}Val]
Meter=String
FontFace=#fMono#
FontSize=15
StringStyle=Bold
FontColor={'#cFg#' if key == 'Down' else '#cMid#'}
AntiAlias=1
X={x0+10}
Y=70
Text=--

[{key}Sub]
Meter=String
MeterStyle=sCap
StringCase=None
X={x0+10}
Y=99
W=180
H=12
ClipString=1
Text=
"""
spd += f"""
[MGraphBox]
Meter=Shape
Shape=Rectangle 18.5,124.5,{W-37},70 | Fill Color #cAlt# | StrokeWidth 1 | Stroke Color #cFg#

[MGraph]
Meter=Line
MeasureName=mDown
MeasureName2=mUp
LineCount=2
LineColor=#cFg#
LineColor2=#cMid#
LineWidth=1.5
AutoScale=1
AntiAlias=1
X=20
Y=126
W={W-40}
H=67

[MLegend]
Meter=String
MeterStyle=sCap
X={W-18}
Y={H-22}
StringAlign=Right
Text=~7 min  /  ink down  /  grey up
"""
(ROOT / "Speed").mkdir(exist_ok=True)
(ROOT / "Speed" / "Speed.ini").write_text(spd, encoding="utf-8")

# ========================================================================= VPN
W, H = 440, 256
vpn = frame("VPN", "Shows which VPN (Proton, Mullvad, Net // Works or another tunnel) is connected and whether it actually carries your traffic.",
            "VPN", "// which tunnel carries your traffic", W, H,
            extra_rainmeter="OnRefreshAction=[!CommandMeasure mRun \"Run\"]\nContextTitle=Check now\nContextAction=[!CommandMeasure mRun \"Run\"]\n",
            measures=runcommand("VPN.ps1") + script("VPN.lua"))
vpn += f"""
[MStatusBox]
Meter=Shape
Shape=Rectangle 19,51,402,46 | Fill Color #cBg# | StrokeWidth 2 | Stroke Color #cMid#

[MStatusCap]
Meter=String
MeterStyle=sCap
X=28
Y=57
Text=checking...

[MStatusVal]
Meter=String
FontFace=#fMono#
FontSize=13
StringStyle=Bold
StringCase=Upper
FontColor=#cFg#
AntiAlias=1
ClipString=1
X=28
Y=70
W=384
H=22
Text=--

[MHeadBar]
Meter=Shape
Shape=Rectangle 18,108,{W-36},18 | Fill Color #cFg# | StrokeWidth 0

[MHeadName]
Meter=String
MeterStyle=sHead
X=24
Y=111
Text=VPN

[MHeadState]
Meter=String
MeterStyle=sHead
X=180
Y=111
Text=State

[MHeadIp]
Meter=String
MeterStyle=sHead
StringAlign=Right
X={W-24}
Y=111
Text=Tunnel IP
"""
vpn += table_rows([("RProton", "Proton VPN"), ("RMullvad", "Mullvad"), ("RNetWorks", "Net // Works VPN"), ("ROther", "Other tunnel")],
                  128, W, [("Name", 24, "L", "@label", "sCell"), ("State", 180, "L", "...", "sCell"), ("Ip", W - 24, "R", "-", "sCell")], row_h=22)
(ROOT / "VPN").mkdir(exist_ok=True)
(ROOT / "VPN" / "VPN.ini").write_text(vpn, encoding="utf-8")

# ======================================================================= WI-FI
W, H = 340, 264
wifi = frame("Wi-Fi", "Wi-Fi network name, signal strength (with thresholds), security, channel and link rates from netsh.",
             "Wi-Fi", "// signal", W, H,
             extra_rainmeter="OnRefreshAction=[!CommandMeasure mRun \"Run\"]\nContextTitle=Open Wi-Fi settings\nContextAction=[\"ms-settings:network-wifi\"]\n",
             measures="""; Signal colour steps ink -> yellow -> red below these percentages.
SignalWarn=60
SignalCrit=35
@@VARS@@""" + runcommand("WiFi.ps1") + script("WiFi.lua"))
wifi += f"""
[MNetBox]
Meter=Shape
Shape=Rectangle 19,51,{W-38},68 | Fill Color #cBg# | StrokeWidth 2 | Stroke Color #cFg#

[MNetCap]
Meter=String
MeterStyle=sCap
X=28
Y=57
Text=Network

[MSsid]
Meter=String
FontFace=#fMono#
FontSize=13
StringStyle=Bold
FontColor=#cFg#
AntiAlias=1
ClipString=1
X=28
Y=70
W=200
H=22
Text=--

[MSec]
Meter=String
MeterStyle=sCap
StringCase=None
ClipString=1
X=28
Y=100
W=210
H=12
Text=
"""
for i in range(1, 6):
    bh = 6 + (i - 1) * 5
    wifi += f"""
[MBar{i}]
Meter=Image
X={258 + (i - 1) * 11}
Y={84 - bh}
W=8
H={bh}
SolidColor=#cTrack#
"""
wifi += f"""
[MSig]
Meter=String
FontFace=#fMono#
FontSize=10
StringStyle=Bold
StringAlign=Right
FontColor=#cFg#
AntiAlias=1
X={W-28}
Y=87
Text=--

[MDbm]
Meter=String
MeterStyle=sCap
StringCase=None
StringAlign=Right
X={W-28}
Y=104
Text=

[MHeadBar]
Meter=Shape
Shape=Rectangle 18,128,{W-36},18 | Fill Color #cFg# | StrokeWidth 0

[MHeadText]
Meter=String
MeterStyle=sHead
X=24
Y=131
Text=Link detail
"""
for i, (base, label) in enumerate([("VChan", "Channel"), ("VRx", "Receive"), ("VTx", "Transmit"), ("VAdapter", "Adapter")]):
    y = 148 + i * 20
    if i % 2 == 1:
        wifi += f"""
[{base}Bg]
Meter=Image
X=18
Y={y}
W={W-36}
H=20
SolidColor=#cAlt#
"""
    wifi += f"""
[{base}Lab]
Meter=String
MeterStyle=sCap
X=24
Y={y+6}
Text={label}

[{base}]
Meter=String
MeterStyle=sCell
StringAlign=Right
X={W-24}
Y={y+4}
W=220
H=14
Text=-
"""
(ROOT / "WiFi").mkdir(exist_ok=True)
(ROOT / "WiFi" / "WiFi.ini").write_text(wifi, encoding="utf-8")
print("written: Speed/Speed.ini, VPN/VPN.ini, WiFi/WiFi.ini")
