"""Generates the Net // Works Speed, VPN, Wi-Fi / Eth, Homelab, Sites, Talkers, Egress / ingress, Wi-Fi survey, LAN
and Deadlines cards (shared frame and styles).
Run from anywhere; writes into the skin folders next to @Resources."""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]


def frame(name, info, title, hint, w, h, extra_rainmeter="", measures=""):
    r = w - 18
    return f"""; Net // Works {title} card. Generated by @Resources\\Tools\\generate_net_cards.py
[Rainmeter]
Update=1000
AccurateText=1
DynamicWindowSize=0
{extra_rainmeter}
[Metadata]
Name=Net // Works {name}
Author=ringmast4r
Information={info}
Version=1.0
License=Creative Commons BY-NC-SA 4.0

[Variables]
; Theme is toggled by the button in the top-right corner.
Theme=dark
@Include=#@#Themes\\SinCity-#Theme#.inc
fMono=Courier New
{measures.split('@@VARS@@')[0] if '@@VARS@@' in measures else ''}
; ================= styles
[sCap]
FontFace=#fMono#
FontSize=7
StringStyle=Bold
StringCase=Upper
FontColor=#cMid#
AntiAlias=1

[sHead]
FontFace=#fMono#
FontSize=7
StringStyle=Bold
StringCase=Upper
FontColor=#cBg#
AntiAlias=1

[sCell]
FontFace=#fMono#
FontSize=8
StringStyle=Bold
FontColor=#cFg#
AntiAlias=1
ClipString=1

[sBtn]
FontFace=#fMono#
FontSize=7
StringStyle=Bold
StringAlign=Right
FontColor=#cFg#
SolidColor=#cTrack#
Padding=6,3,6,3
AntiAlias=1
MouseActionCursorName=Hand
{measures.split('@@VARS@@')[1] if '@@VARS@@' in measures else measures}
; ================= card
[MCard]
Meter=Shape
Shape=Rectangle 1.5,1.5,{w-3},{h-3} | Fill Color #cBg# | StrokeWidth 3 | Stroke Color #cFg#
Shape2=Rectangle 18,38,{w-36},3 | Fill Color #cFg# | StrokeWidth 0
Shape3=Rectangle 18,{h-32},{w-36},2 | Fill Color #cFg# | StrokeWidth 0

[MTitle]
Meter=String
FontFace=#fMono#
FontSize=11
StringStyle=Bold
StringCase=Upper
FontColor=#cFg#
AntiAlias=1
X=18
Y=15
Text={title}

[MHint]
Meter=String
MeterStyle=sCap
X={18 + 13 * len(title) + 14}
Y=18
Text={hint}

[MToggle]
Meter=String
MeterStyle=sBtn
X={r - 6}
Y=16
Text=#ToggleLabel#
LeftMouseUpAction=[!WriteKeyValue Variables Theme #ToggleTo#][!Refresh]
ToolTipText=Switch to #ToggleTo# mode

[MFoot]
Meter=String
MeterStyle=sCap
StringCase=None
X=18
Y={h-22}
Text=starting...
"""


def runcommand(script, finish="Parse()", args=""):
    return f"""
; ================= measures
[mRun]
Measure=Plugin
Plugin=RunCommand
Program=powershell.exe
Parameter=-NoProfile -ExecutionPolicy Bypass -File "#@#Scripts\\{script}"{args}
State=Hide
OutputType=UTF8
Timeout=20000
FinishAction=[!CommandMeasure mScript "{finish}"]
"""


def script(lua):
    return f"""
[mScript]
Measure=Script
ScriptFile=#@#Scripts\\{lua}
"""


def table_rows(rows, y0, w, cols, row_h=20, prefix=""):
    """rows: list of (meter_base, label); cols: list of (suffix, x, align, default)."""
    s = ""
    for i, (base, label) in enumerate(rows):
        y = y0 + i * row_h
        if i % 2 == 1:
            s += f"""
[{base}Bg]
Meter=Image
X=18
Y={y}
W={w-36}
H={row_h}
SolidColor=#cAlt#
"""
        for suffix, x, align, default, style in cols:
            text = label if default == "@label" else default
            s += f"""
[{base}{suffix}]
Meter=String
MeterStyle={style}
X={x}
Y={y + (6 if style == 'sCap' else 4)}
{"StringAlign=Right" if align == "R" else ""}
W={170 if suffix in ('Name', 'State') else 230}
H=14
Text={text}
"""
    return s


# ======================================================================= SPEED
W, H = 440, 236
spd = frame("Speed", "Live download and upload speed on the best-route adapter, with a ~7 minute graph, peaks and data used.",
            "Speed", "// live traffic", W, H,
            measures="""
; ================= measures
[mDown]
Measure=NetIn
Interface=Best

[mUp]
Measure=NetOut
Interface=Best
""" + script("Speed.lua"))
for i, (key, cap) in enumerate([("Down", "Download"), ("Up", "Upload")]):
    x0 = 18 + i * 206
    spd += f"""
[{key}Box]
Meter=Shape
Shape=Rectangle {x0+1},51,{196},{64} | Fill Color #cBg# | StrokeWidth 2 | Stroke Color #cFg#

[{key}Cap]
Meter=String
MeterStyle=sCap
X={x0+10}
Y=57
Text={cap}

[{key}Val]
Meter=String
FontFace=#fMono#
FontSize=15
StringStyle=Bold
FontColor={'#cFg#' if key == 'Down' else '#cMid#'}
AntiAlias=1
X={x0+10}
Y=70
Text=--

[{key}Sub]
Meter=String
MeterStyle=sCap
StringCase=None
X={x0+10}
Y=99
W=180
H=12
ClipString=1
Text=
"""
spd += f"""
[MGraphBox]
Meter=Shape
Shape=Rectangle 18.5,124.5,{W-37},70 | Fill Color #cAlt# | StrokeWidth 1 | Stroke Color #cFg#

[MGraph]
Meter=Line
MeasureName=mDown
MeasureName2=mUp
LineCount=2
LineColor=#cFg#
LineColor2=#cMid#
LineWidth=1.5
AutoScale=1
AntiAlias=1
X=20
Y=126
W={W-40}
H=67

[MLegend]
Meter=String
MeterStyle=sCap
X={W-18}
Y={H-22}
StringAlign=Right
Text=~7 min  /  ink down  /  grey up
"""
(ROOT / "Speed").mkdir(exist_ok=True)
(ROOT / "Speed" / "Speed.ini").write_text(spd, encoding="utf-8")

# ========================================================================= VPN
W, H = 440, 256
vpn = frame("VPN", "Shows which VPN (Proton, Mullvad, Net // Works or another tunnel) is connected and whether it actually carries your traffic.",
            "VPN", "// which tunnel carries your traffic", W, H,
            extra_rainmeter="OnRefreshAction=[!CommandMeasure mRun \"Run\"]\nContextTitle=Check now\nContextAction=[!CommandMeasure mRun \"Run\"]\n",
            measures=runcommand("VPN.ps1") + script("VPN.lua"))
vpn += f"""
[MStatusBox]
Meter=Shape
Shape=Rectangle 19,51,402,46 | Fill Color #cBg# | StrokeWidth 2 | Stroke Color #cMid#

[MStatusCap]
Meter=String
MeterStyle=sCap
X=28
Y=57
Text=checking...

[MStatusVal]
Meter=String
FontFace=#fMono#
FontSize=13
StringStyle=Bold
StringCase=Upper
FontColor=#cFg#
AntiAlias=1
ClipString=1
X=28
Y=70
W=384
H=22
Text=--

[MHeadBar]
Meter=Shape
Shape=Rectangle 18,108,{W-36},18 | Fill Color #cFg# | StrokeWidth 0

[MHeadName]
Meter=String
MeterStyle=sHead
X=24
Y=111
Text=VPN

[MHeadState]
Meter=String
MeterStyle=sHead
X=180
Y=111
Text=State

[MHeadIp]
Meter=String
MeterStyle=sHead
StringAlign=Right
X={W-24}
Y=111
Text=Tunnel IP
"""
vpn += table_rows([("RProton", "Proton VPN"), ("RMullvad", "Mullvad"), ("RNetWorks", "Net // Works VPN"), ("ROther", "Other tunnel")],
                  128, W, [("Name", 24, "L", "@label", "sCell"), ("State", 180, "L", "...", "sCell"), ("Ip", W - 24, "R", "-", "sCell")], row_h=22)
(ROOT / "VPN").mkdir(exist_ok=True)
(ROOT / "VPN" / "VPN.ini").write_text(vpn, encoding="utf-8")

# ================================================================= WI-FI / ETH
W, H = 340, 264
wifi = frame("Wi-Fi / Eth", "Wi-Fi (wlan) or Ethernet (eth), switched by the WI-FI / ETH buttons. Wi-Fi: network name, signal "
             "strength (with thresholds), security, channel and link rates from netsh. Ethernet: adapter, link speed, duplex, "
             "IPv4, gateway, DNS and MAC.",
             "Wi-Fi / Eth", "", W, H,
             extra_rainmeter="OnRefreshAction=[!CommandMeasure mRun \"Run\"]\nContextTitle=Open Wi-Fi settings\nContextAction=[\"ms-settings:network-wifi\"]\n"
                             "ContextTitle2=Open Ethernet settings\nContextAction2=[\"ms-settings:network-ethernet\"]\n",
             measures="""; Which link the card shows: wifi or eth. Set by the WI-FI / ETH switch.
Mode=wifi
; Signal colour steps ink -> yellow -> red below these percentages.
SignalWarn=60
SignalCrit=35
@@VARS@@""" + runcommand("WiFi.ps1", args=" -Mode #Mode#") + script("WiFi.lua"))
for meter, label, val, x, tip in [("MModeWifi", "Wi-Fi", "wifi", W - 110, "Show the wireless link (wlan)"),
                                  ("MModeEth", "Eth", "eth", W - 78, "Show the wired link (eth)")]:
    wifi += f"""
[{meter}]
Meter=String
MeterStyle=sBtn
StringCase=Upper
X={x}
Y=16
Text={label}
LeftMouseUpAction=[!WriteKeyValue Variables Mode {val}][!Refresh]
ToolTipText={tip}
"""
wifi += f"""
[MNetBox]
Meter=Shape
Shape=Rectangle 19,51,{W-38},68 | Fill Color #cBg# | StrokeWidth 2 | Stroke Color #cFg#

[MNetCap]
Meter=String
MeterStyle=sCap
X=28
Y=57
Text=Network

[MSsid]
Meter=String
FontFace=#fMono#
FontSize=13
StringStyle=Bold
FontColor=#cFg#
AntiAlias=1
ClipString=1
X=28
Y=70
W=200
H=22
Text=--

[MSec]
Meter=String
MeterStyle=sCap
StringCase=None
ClipString=1
X=28
Y=100
W=210
H=12
Text=
"""
for i in range(1, 6):
    bh = 6 + (i - 1) * 5
    wifi += f"""
[MBar{i}]
Meter=Image
X={258 + (i - 1) * 11}
Y={84 - bh}
W=8
H={bh}
SolidColor=#cTrack#
"""
wifi += f"""
[MSig]
Meter=String
FontFace=#fMono#
FontSize=10
StringStyle=Bold
StringAlign=Right
FontColor=#cFg#
AntiAlias=1
X={W-28}
Y=87
Text=--

[MDbm]
Meter=String
MeterStyle=sCap
StringCase=None
StringAlign=Right
X={W-28}
Y=104
Text=

[MHeadBar]
Meter=Shape
Shape=Rectangle 18,128,{W-36},18 | Fill Color #cFg# | StrokeWidth 0

[MHeadText]
Meter=String
MeterStyle=sHead
X=24
Y=131
Text=Link detail
"""
for i, (base, label) in enumerate([("VChan", "Channel"), ("VRx", "Receive"), ("VTx", "Transmit"), ("VAdapter", "Adapter")]):
    y = 148 + i * 20
    if i % 2 == 1:
        wifi += f"""
[{base}Bg]
Meter=Image
X=18
Y={y}
W={W-36}
H=20
SolidColor=#cAlt#
"""
    wifi += f"""
[{base}Lab]
Meter=String
MeterStyle=sCap
X=24
Y={y+6}
Text={label}

[{base}]
Meter=String
MeterStyle=sCell
StringAlign=Right
X={W-24}
Y={y+4}
W=220
H=14
Text=-
"""
(ROOT / "WiFi-Eth").mkdir(exist_ok=True)
(ROOT / "WiFi-Eth" / "WiFi-Eth.ini").write_text(wifi, encoding="utf-8")


# =================================================================== LAB CARDS
# Homelab, Sites, Talkers, Egress-Ingress, WiFi-Survey, LAN and Deadlines. Personal settings live in @Resources\Local\
# (never committed); @Resources\Examples\ holds the shipped templates. Shared Lua: Scripts\Common.lua.
def write(folder, text):
    (ROOT / folder).mkdir(exist_ok=True)
    (ROOT / folder / f"{folder}.ini").write_text(text, encoding="utf-8")


def context(*items):
    """items: (title, action) pairs for the right-click menu."""
    s = ""
    for i, (title, action) in enumerate(items):
        n = "" if i == 0 else str(i + 1)
        s += f"ContextTitle{n}={title}\nContextAction{n}={action}\n"
    return s


RUN_NOW = '[!CommandMeasure mRun "Run"]'
ON_REFRESH = f"OnRefreshAction={RUN_NOW}\n"
# Mouse wheel anywhere on the card calls the Lua script's Scroll(); for lists longer than the table (see scrollbar()).
SCROLL = ('MouseScrollUpAction=[!CommandMeasure mScript "Scroll(-1)"]\n'
          'MouseScrollDownAction=[!CommandMeasure mScript "Scroll(1)"]\n')


def statboxes(boxes, y, W, h=64, hit=None):
    """Stat boxes across the card, the Speed card's look: caption, big value, small sub line.
    hit: {key: (action, tooltip)} makes those boxes clickable."""
    gap = 8
    bw = (W - 36 - gap * (len(boxes) - 1)) / len(boxes)
    s = ""
    for i, (key, cap) in enumerate(boxes):
        x0 = round(18 + i * (bw + gap))
        s += f"""
[{key}Box]
Meter=Shape
Shape=Rectangle {x0+1},{y},{round(bw)-2},{h} | Fill Color #cBg# | StrokeWidth 2 | Stroke Color #cFg#

[{key}Cap]
Meter=String
MeterStyle=sCap
X={x0+10}
Y={y+6}
Text={cap}

[{key}Val]
Meter=String
FontFace=#fMono#
FontSize=15
StringStyle=Bold
FontColor=#cFg#
AntiAlias=1
ClipString=1
X={x0+10}
Y={y+19}
W={round(bw)-20}
H=26
Text=--

[{key}Sub]
Meter=String
MeterStyle=sCap
StringCase=None
ClipString=1
X={x0+10}
Y={y+48}
W={round(bw)-20}
H=12
Text=
"""
        if hit and key in hit:
            s += f"""
[{key}Hit]
Meter=Image
X={x0+1}
Y={y}
W={round(bw)-2}
H={h}
SolidColor=0,0,0,1
LeftMouseUpAction={hit[key][0]}
ToolTipText={hit[key][1]}
MouseActionCursorName=Hand
"""
    return s


def status_box(y, W, h=46):
    """The VPN card's banner: caption + one big line. Lua restyles it per state."""
    return f"""
[MStatusBox]
Meter=Shape
Shape=Rectangle 19,{y},{W-38},{h} | Fill Color #cBg# | StrokeWidth 2 | Stroke Color #cMid#

[MStatusCap]
Meter=String
MeterStyle=sCap
X=28
Y={y+6}
Text=checking...

[MStatusVal]
Meter=String
FontFace=#fMono#
FontSize=13
StringStyle=Bold
StringCase=Upper
FontColor=#cFg#
AntiAlias=1
ClipString=1
X=28
Y={y+19}
W={W-56}
H=22
Text=--
"""


def gtable(prefix, n, y0, W, cols, row_h=20, hit=False):
    """Ink header bar at y0, then n rows named <prefix><i><key>. cols: (key, header, x, 'L'|'R', width)."""
    s = f"""
[{prefix}HeadBar]
Meter=Shape
Shape=Rectangle 18,{y0},{W-36},18 | Fill Color #cFg# | StrokeWidth 0
"""
    for key, head, x, align, w in cols:
        s += f"""
[{prefix}Head{key}]
Meter=String
MeterStyle=sHead
{"StringAlign=Right" if align == "R" else ""}
X={x}
Y={y0+3}
Text={head}
"""
    for i in range(1, n + 1):
        y = y0 + 20 + (i - 1) * row_h
        if i % 2 == 0:
            s += f"""
[{prefix}{i}Bg]
Meter=Image
X=18
Y={y}
W={W-36}
H={row_h}
SolidColor=#cAlt#
"""
        if hit:
            s += f"""
[{prefix}{i}Hit]
Meter=Image
X=18
Y={y}
W={W-36}
H={row_h}
SolidColor=0,0,0,1
"""
        for key, head, x, align, w in cols:
            s += f"""
[{prefix}{i}{key}]
Meter=String
MeterStyle=sCell
{"StringAlign=Right" if align == "R" else ""}
X={x}
Y={y+4}
W={w}
H=14
Text=
"""
    return s


def scrollbar(prefix, n, y0, W, H, row_h=20):
    """Track and thumb down the right edge of a gtable, plus a 'rows a-b of n' note in the footer. Hidden until
    the Lua script holds more rows than the table shows; Lua moves the thumb (Shape2) and fills the note."""
    return f"""
[{prefix}Scroll]
Meter=Shape
Shape=Rectangle {W-21},{y0+20},3,{n*row_h} | Fill Color #cTrack# | StrokeWidth 0
Shape2=Rectangle {W-21},{y0+20},3,{n*row_h} | Fill Color #cFg# | StrokeWidth 0
Hidden=1

[MScroll]
Meter=String
MeterStyle=sCap
StringCase=None
StringAlign=Right
X={W-18}
Y={H-22}
Text=
"""


def table_height(y0, n, row_h=20):
    return y0 + 20 + n * row_h + 8 + 32


# ------------------------------------------------------------------- HOMELAB
W = 600
GCOLS, GROWS, PITCH = 40, 5, 14
grid_y = 140
tbl_y = grid_y + GROWS * PITCH + 10
H = table_height(tbl_y, 12)
lab = frame("Homelab", "Proxmox host health and every guest: host CPU, memory, IO wait and load, one dot per container or VM, "
            "and the guests that are down or busiest. One SSH call with your own key to the host set in @Resources\\Local\\homelab.txt.",
            "Homelab", "// proxmox", W, H,
            extra_rainmeter=ON_REFRESH + context(("Check now", RUN_NOW), ("Set the Proxmox host", '["#@#Local\\homelab.txt"]')),
            measures=runcommand("Homelab.ps1") + script("Homelab.lua"))
lab += statboxes([("Cpu", "Host CPU"), ("Mem", "Memory"), ("Wait", "IO wait"), ("Guests", "Guests running")], 51, W)
lab += f"""
[MGridCap]
Meter=String
MeterStyle=sCap
X=18
Y={grid_y - 14}
Text=All guests  /  ink running  /  yellow busy  /  red down  /  grey off
"""
for i in range(GCOLS * GROWS):
    r, c = divmod(i, GCOLS)
    lab += f"""
[D{i+1}]
Meter=Image
X={19 + c * PITCH}
Y={grid_y + r * PITCH}
W={PITCH - 3}
H={PITCH - 3}
SolidColor=#cTrack#
Hidden=1
"""
lab += gtable("R", 12, tbl_y, W, [("Id", "ID", 24, "L", 40), ("Name", "Guest", 66, "L", 180), ("State", "State", 254, "L", 70),
                                  ("Cpu", "CPU", 372, "R", 50), ("Mem", "Memory", 500, "R", 120), ("Up", "Uptime", W - 24, "R", 66)])
write("Homelab", lab)

# --------------------------------------------------------------------- SITES
W = 440
tbl_y = 108
H = table_height(tbl_y, 16)
sites = frame("Sites up", "Status code and response time for every site in @Resources\\Local\\sites.txt, checked in parallel once a "
              "minute. Worst first: down, error, then slowest. Scroll for the rest of a long list. Click a row to open the site.",
              "Sites up", "// http status, worst first", W, H,
              extra_rainmeter=ON_REFRESH + SCROLL + context(("Check now", RUN_NOW), ("Edit the site list", '["#@#Local\\sites.txt"]')),
              measures=runcommand("Sites.ps1") + script("Sites.lua"))
sites += status_box(51, W)
sites += gtable("R", 16, tbl_y, W, [("Site", "Site", 24, "L", 250), ("Code", "Code", 318, "R", 40), ("Ms", "Time", 376, "R", 54),
                                    ("State", "State", W - 24, "R", 52)], hit=True)
sites += scrollbar("R", 16, tbl_y, W, H)
write("Sites", sites)

# ------------------------------------------------------------------- TALKERS
W = 600
tbl_y = 124
H = table_height(tbl_y, 16)
talk = frame("Who's talking", "Which programs hold connections to the internet, and to whom: owner network, city and country, port "
             "and count. Addresses are looked up offline in IP // Revealer when it is installed (path in @Resources\\Local\\talkers.txt); "
             "threat-listed addresses turn red.", "Who's talking", "// outbound connections", W, H,
             extra_rainmeter=ON_REFRESH + context(("Check now", RUN_NOW), ("Set the IP // Revealer path", '["#@#Local\\talkers.txt"]')),
             measures=runcommand("Talkers.ps1") + script("Talkers.lua"))
talk += statboxes([("Conns", "Connections"), ("Hosts", "Remote hosts"), ("Procs", "Programs"), ("Flag", "Threat-listed")], 51, W)
talk += gtable("R", 16, tbl_y, W, [("Proc", "Program", 24, "L", 108), ("Ip", "Remote", 136, "L", 120), ("Org", "Owner", 260, "L", 140),
                                   ("Where", "Where", 404, "L", 96), ("Port", "Port", W - 56, "R", 40), ("N", "N", W - 24, "R", 26)])
write("Talkers", talk)

# ---------------------------------------------------------- EGRESS / INGRESS
W = 600
tbl_y = 124
H = table_height(tbl_y, 16)
flow = frame("Egress / ingress", "What is going where: every connection this PC holds, split into outbound (this PC called out) and "
             "inbound (something connected in), plus the ports it listens on. Inbound from the internet is red, from the LAN "
             "yellow, threat-listed addresses red. Click a box to show only that kind; scroll for the rest. The header is "
             "live traffic out and in. Owners come from IP // Revealer (path in @Resources\\Local\\talkers.txt), LAN names from "
             "the LAN and Homelab cards.", "Egress / ingress", "// what is going where", W, H,
             extra_rainmeter=ON_REFRESH + SCROLL + context(("Check now", RUN_NOW), ("Set the IP // Revealer path", '["#@#Local\\talkers.txt"]'),
                                                           ("Name LAN devices", '["#@#Local\\lan_names.txt"]')),
             measures=runcommand("Flows.ps1") + """
[mIn]
Measure=NetIn
Interface=Best

[mOut]
Measure=NetOut
Interface=Best
""" + script("Flows.lua"))


def view(kind, what):
    return (f"""[!CommandMeasure mScript "View('{kind}')"]""", f"Show only {what}; click again for everything")


flow += statboxes([("Out", "Outbound"), ("In", "Inbound"), ("Lis", "Listening"), ("Flag", "Threat-listed")], 51, W,
                  hit={"Out": view("out", "outbound connections"), "In": view("in", "inbound connections"),
                       "Lis": view("listen", "listening ports, including the ones only this PC can reach"),
                       "Flag": view("flag", "threat-listed addresses")})
flow += gtable("R", 16, tbl_y, W, [("Dir", "Dir", 24, "L", 46), ("Proc", "Program", 74, "L", 104), ("Peer", "Peer", 182, "L", 136),
                                   ("Who", "Who / what", 322, "L", 150), ("Port", "Port", W - 62, "R", 62), ("N", "N", W - 24, "R", 30)])
flow += scrollbar("R", 16, tbl_y, W, H)
write("Egress-Ingress", flow)

# --------------------------------------------------------------- WI-FI SURVEY
W = 600
CH24 = list(range(1, 14))
CH5 = [36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 149, 153, 157, 161, 165]
tbl_y = 140
H = table_height(tbl_y, 15)
srv = frame("Wi-Fi survey", "Every Wi-Fi network in range: name, access point vendor (from its BSSID), channel, band, signal and "
            "security, plus how crowded each 2.4 and 5 GHz channel is. Asks Windows for a fresh scan each cycle.",
            "Wi-Fi survey", "// networks in range", W, H,
            extra_rainmeter=ON_REFRESH + context(("Scan now", RUN_NOW)),
            measures=runcommand("Survey.ps1") + script("Survey.lua"))
srv += """
[sTick]
FontFace=#fMono#
FontSize=6
StringStyle=Bold
StringAlign=Center
FontColor=#cMid#
AntiAlias=1

[MBand24Box]
Meter=Shape
Shape=Rectangle 19,51,190,78 | Fill Color #cBg# | StrokeWidth 2 | Stroke Color #cFg#

[MBand24Cap]
Meter=String
MeterStyle=sCap
X=28
Y=57
Text=2.4 GHz

[MBand5Box]
Meter=Shape
Shape=Rectangle 217,51,364,78 | Fill Color #cBg# | StrokeWidth 2 | Stroke Color #cFg#

[MBand5Cap]
Meter=String
MeterStyle=sCap
X=226
Y=57
Text=5 GHz
"""
for band, chans, x0, pitch, bw, ticks in [("24", CH24, 28, 13, 9, CH24), ("5", CH5, 226, 14, 10, [36, 52, 100, 120, 149, 165])]:
    for k, ch in enumerate(chans):
        x = x0 + k * pitch
        srv += f"""
[C{band}_{ch}]
Meter=Image
X={x}
Y=109
W={bw}
H=2
SolidColor=#cTrack#
ToolTipText=channel {ch}
"""
        if ch in ticks:
            srv += f"""
[L{band}_{ch}]
Meter=String
MeterStyle=sTick
X={x + bw // 2}
Y=114
Text={ch}
"""
srv += gtable("R", 15, tbl_y, W, [("Ssid", "Network", 24, "L", 150), ("Vendor", "Access point vendor", 178, "L", 146),
                                  ("Ch", "Ch", 356, "R", 28), ("Band", "Band", 364, "L", 56), ("Sig", "Signal", 464, "R", 40),
                                  ("Sec", "Security", 472, "L", 108)])
write("WiFi-Survey", srv)

# ----------------------------------------------------------------------- LAN
W = 600
tbl_y = 124
H = table_height(tbl_y, 16)
lan = frame("LAN watch", "Every device on your local network from a ping sweep every 5 minutes: address, name, vendor (from its MAC) "
            "and when it was first seen. Devices first seen in the last 24 hours turn yellow. Label devices in "
            "@Resources\\Local\\lan_names.txt; Proxmox containers are named by the Homelab card.", "LAN watch", "// local network", W, H,
            extra_rainmeter=ON_REFRESH + context(("Sweep now", '[!CommandMeasure mSweep "Run"]'), ("Name devices", '["#@#Local\\lan_names.txt"]')),
            measures=runcommand("Lan.ps1") + """
[mSweep]
Measure=Plugin
Plugin=RunCommand
Program=powershell.exe
Parameter=-NoProfile -ExecutionPolicy Bypass -File "#@#Scripts\\Lan.ps1" -Sweep
State=Hide
OutputType=UTF8
Timeout=30000
FinishAction=[!CommandMeasure mScript "Parse('mSweep')"]
""" + script("Lan.lua"))
lan += statboxes([("Dev", "Devices"), ("New", "New today"), ("Ct", "Containers"), ("Net", "Subnet")], 51, W)
lan += gtable("R", 16, tbl_y, W, [("Ip", "IP", 24, "L", 88), ("Name", "Name", 114, "L", 150), ("Vendor", "Vendor", 268, "L", 146),
                                  ("Mac", "MAC", 418, "L", 110), ("Seen", "Seen", W - 24, "R", 44)])
write("LAN", lan)

# ----------------------------------------------------------------- DEADLINES
W = 340
tbl_y = 130
H = table_height(tbl_y, 6)
dl = frame("Deadlines", "Countdown to the dates in @Resources\\Local\\deadlines.txt (one per line: 2026-10-11 | Name). Yellow inside "
           "30 days, red inside 7.", "Deadlines", "// countdown", W, H,
           extra_rainmeter=context(("Edit deadlines", '["#@#Local\\deadlines.txt"]')),
           measures=script("Deadlines.lua"))
dl += f"""
[MNextBox]
Meter=Shape
Shape=Rectangle 19,51,{W-38},68 | Fill Color #cBg# | StrokeWidth 2 | Stroke Color #cFg#

[MNextCap]
Meter=String
MeterStyle=sCap
X=28
Y=57
Text=Next

[MNextName]
Meter=String
FontFace=#fMono#
FontSize=13
StringStyle=Bold
FontColor=#cFg#
AntiAlias=1
ClipString=1
X=28
Y=70
W=200
H=22
Text=--

[MNextDate]
Meter=String
MeterStyle=sCap
StringCase=None
X=28
Y=100
Text=

[MNextDays]
Meter=String
FontFace=#fMono#
FontSize=22
StringStyle=Bold
StringAlign=Right
FontColor=#cFg#
AntiAlias=1
X={W-28}
Y=60
Text=--

[MNextUnit]
Meter=String
MeterStyle=sCap
StringAlign=Right
X={W-28}
Y=100
Text=days
"""
dl += gtable("R", 6, tbl_y, W, [("Name", "Deadline", 24, "L", 170), ("Date", "Date", 200, "L", 80), ("Days", "Days", W - 24, "R", 36)])
write("Deadlines", dl)

print("written: Speed, VPN, WiFi-Eth, Homelab, Sites, Talkers, Egress-Ingress, WiFi-Survey, LAN, Deadlines")
