[Rainmeter]
Update=1000
BackgroundMode=0
AccurateText=1
DynamicWindowSize=1
KeepOnScreen=0

[Metadata]
Name=Chile Time Display
Author=Patrick Quirk
Information=Time display for Chile CLT timezone
License=Open Source
Version=1.0.0

[Variables]
fontName=Consolas
timeSize=120
dateSize=36
labelSize=28
colorTime=255,255,255,255
colorDate=0,57,166,255
colorLabel=213,43,30,255
colorBackground=0,0,0,255

; ----------------------------------
; MEASURES
; ----------------------------------

[MeasureTime]
Measure=Time
TimeZone=-3
DaylightSavingTime=0
Format=%I:%M %p

[MeasureDate]
Measure=Time
TimeZone=-3
DaylightSavingTime=0
Format=%a, %b %d

[MeasureDay]
Measure=Time
TimeZone=-3
DaylightSavingTime=0
Format=%A

; ----------------------------------
; METERS
; ----------------------------------

[MeterLabel]
Meter=String
X=0
Y=0
FontFace=#fontName#
FontSize=#labelSize#
FontColor=#colorLabel#
StringAlign=Left
StringCase=Upper
AntiAlias=1
MeasureName=MeasureDay
StringStyle=Bold
Text=Chile CLT, %1

[MeterTime]
Meter=String
MeasureName=MeasureTime
X=0
Y=8
FontFace=#fontName#
FontSize=#timeSize#
FontColor=#colorTime#
StringAlign=Left
AntiAlias=1
StringStyle=Bold
StringEffect=Shadow
FontEffectColor=213,43,30,50
Text=%1

