[Rainmeter]
Author=achfighter
Update=360
LeftMouseDoubleClickAction=!RainmeterDeactivateConfig

[Metadata]
Name=RAMgauge
Information=Graphical indicator for RAM Usage 
License=Free for Personal Use in Creative Common, Not Allowed Commerical Use! If you are using this widget, you agree to "License" agreement. 
Version=v0.3

[Variables]
FontName=Segoe WP Semibold
FontColor=90,90,90,225
FontSize=13
Image=#CURRENTPATH#rambackground.png
Image=#CURRENTPATH#ramrotator.png

[MeasureRAM]
Measure=PhysicalMemory

[MeasureSWAP]
Measure=SWAPMemory

[MeasureUPTIME]
Measure=Uptime
Substitute="0d":""

[MeasureAngle]
Measure=PhysicalMemory
; (percentages - 1) * (1 / 100)
Formula=(MeasureRAM % 100) * 0,001
Disabled=#percentages#

[MeasureARC]
; Measures the size of used RAM.
Measure=Plugin
Plugin=PerfMon
PerfMonObject=Memory
PerfMonCounter=Percent
PerfMonDifference=0
; 1 / 100
Formula=(MeasureRAM % 100) * 0,001
UpdateDivider=-1

[MeasureRotator]
Measure=PhysicalMemory
; 0 + 1 / 100
Formula=(MeasureArc % 360) * 0,001
UpdateDivider=-1

[MeterRAM]
MeasureName=MeasureRAM
Meter=String
X=40
Y=60
FontFace=#FontName#
FontColor=#FontColor#
FontSize=40
StringEffect=Shadow
FontEffectColor=0,0,0,90
AntiAlias=1
Percentual=1
PostFix="%"
LeftMouseUpAction=!execute [taskmgr.exe]

[TextSWAP]
Meter=String
Text=SWAP
X=50
Y=50
FontFace=#FontName#
FontColor=125,125,125,240
FontSize=#FontSize#
StringEffect=Shadow
FontEffectColor=0,0,0,90
AntiAlias=1
Percentual=1

[MeterSWAP]
MeasureName=MeasureSWAP
Meter=String
X=115
Y=50
FontFace=#FontName#
FontColor=220,220,220,240
FontSize=#FontSize#
StringEffect=Shadow
FontEffectColor=0,0,0,90
AntiAlias=1
Percentual=1
PostFix="%"
LeftMouseUpAction=!execute [taskmgr.exe]

[TextUPTIME]
Meter=String
Text=UPTIME
X=50
Y=125
FontFace=#FontName#
FontColor=125,125,125,240
FontSize=11
StringEffect=Shadow
FontEffectColor=0,0,0,90
AntiAlias=1
Percentual=1

[MeterUPTIME]
MeasureName=MeasureUPTIME
Meter=String
X=107
Y=125
FontFace=#FontName#
FontColor=220,220,220,240
FontSize=11
StringEffect=Shadow
FontEffectColor=0,0,0,90
AntiAlias=1
LeftMouseUpAction=!execute [taskmgr.exe]

[Background Meter]
Meter=Image
ImageName=rambackground
X=0
Y=0
W=200
H=200

[MeterRAMArc]
MeasureName=MeasureRAM
Meter=ROUNDLINE
W=200
H=200
LineStart=75
LineLength=90
LineColor=90,90,90,240
; 1 / 100
StartAngle=(4 / 1 % 360) + 0.7
AntiAlias=1
Solid=1
DynamicVariables=1
UpdateDivider=1

[MeterRAMRotator]
Meter=ROTATOR
MeasureName=MeasureRAM
ImageName=ramrotator
X=0
Y=0
W=200
H=200
OffsetX=100
OffsetY=100
StartAngle=(4 % 360) + 2.27
RotationAngle=6.2832
UpdateDivider=1


