"""Generate Top20.ini for the Top 20 // Processes Rainmeter skin.

Each column is its own leaderboard: the 20 processes eating the most of that
resource, ranked independently (CPU, memory, swap, disk I/O, GPU, VRAM).
Data comes from Rainmeter's built-in UsageMonitor plugin, one perf-counter
thread per category, so 120 ranked measures cost almost nothing.

    py generate.py              (Python 3.10+, from @Resources or by full path)

then refresh the skin. Colors and fonts live in Variables.inc. Hardware facts
(CPU/GPU name, thread count, VRAM size) are read from the registry at
generation time, so rerun this after swapping hardware.
"""
import os
import re
import winreg
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "Top20.ini"

ROWS = 20
PAD, GUTTER, COL_W, GAP = 22, 26, 190, 18
TITLE_Y, RULE_Y, HEAD_Y = 18, 52, 68
LIST_Y, ROW_H = 136, 23
VALUE_W = 66                      # right-hand room kept for the number

GIB = 1073741824
GPU_RAW = 60                      # (process, engine) rows fed to GpuBoard.lua

# key, label, caption, accent var, UsageMonitor options, value kind.
# Options of None = the column is filled by a script instead (GPU: Task
# Manager counts a process's busiest engine, UsageMonitor can only sum them).
COLUMNS = [
    ("CPU", "CPU", "busy time", "Cpu", {"Alias": "CPU", "Percent": "1"}, "pct"),
    ("RAM", "MEMORY", "private working set", "Ram", {"Alias": "RAM"}, "bytes"),
    ("SWAP", "SWAP", "commit charge", "Swap", {"Category": "Process", "Counter": "Page File Bytes"}, "bytes"),
    ("DISK", "DISK I/O", "read + write", "Disk", {"Alias": "IO"}, "rate"),
    ("GPU", "GPU", "busiest engine", "Gpu", None, "pct"),
    ("VRAM", "VRAM", "dedicated", "Vram", {"Alias": "VRAM", "PIDToName": "1"}, "bytes"),
]

# Below this a row counts as idle and is drawn faint.
IDLE = {"pct": "0.05", "bytes": "1", "rate": "1"}


def reg(path, value):
    try:
        with winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, path) as key:
            return winreg.QueryValueEx(key, value)[0]
    except OSError:
        return None


def cpu_name():
    raw = reg(r"HARDWARE\DESCRIPTION\System\CentralProcessor\0", "ProcessorNameString") or "CPU"
    s = re.sub(r"\((R|TM)\)", "", raw)
    s = re.sub(r"\s+CPU\s*@.*$", "", s)
    s = re.sub(r"\s+\d+-Core Processor.*$", "", s)
    s = re.sub(r"^(Intel\s+Core|AMD)\s+", "", s.strip())
    return re.sub(r"\s+", " ", s).strip()


def gpu():
    """Name and dedicated memory of the adapter with the most VRAM."""
    base = r"SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}"
    best_name, best_mem = "GPU", 0
    for i in range(16):
        sub = rf"{base}\{i:04d}"
        name = reg(sub, "DriverDesc")
        if not name:
            continue
        mem = reg(sub, "HardwareInformation.qwMemorySize") or reg(sub, "HardwareInformation.MemorySize") or 0
        if isinstance(mem, bytes):
            mem = int.from_bytes(mem[:8], "little")
        if not isinstance(mem, int):
            mem = 0
        if mem > best_mem or best_name == "GPU":
            best_name, best_mem = name, mem
    short = re.sub(r"^(NVIDIA\s+GeForce|NVIDIA|AMD|Intel\(R\))\s+", "", best_name).strip()
    return short, best_mem


def section(name, *pairs, comment=None):
    lines = [f"; {comment}"] if comment else []
    lines.append(f"[{name}]")
    lines += [f"{k}={v}" for k, v in pairs]
    return "\n".join(lines) + "\n"


def col_x(i):
    return PAD + GUTTER + i * (COL_W + GAP)


def main():
    cpu = cpu_name()
    gpu_name, vram_total = gpu()
    threads = os.cpu_count() or 1

    width = PAD + GUTTER + len(COLUMNS) * COL_W + (len(COLUMNS) - 1) * GAP + PAD
    foot_y = LIST_Y + ROWS * ROW_H + 8
    height = foot_y + 16 + PAD - 6
    right = width - PAD

    out = []
    out.append(section(
        "Rainmeter",
        ("Update", "1000"),
        ("AccurateText", "1"),
        ("@Include", "#@#Variables.inc"),
        ("ContextTitle", "Open Task Manager"),
        ("ContextAction", '["taskmgr.exe"]'),
        ("ContextTitle2", "Open Resource Monitor"),
        ("ContextAction2", '["resmon.exe"]'),
        ("ContextTitle3", "Edit colors and fonts"),
        ("ContextAction3", '["#CONFIGEDITOR#" "#@#Variables.inc"]'),
        comment="GENERATED by @Resources\\generate.py - edit that, not this file.",
    ))
    out.append(section(
        "Metadata",
        ("Name", "Top 20 // Processes"),
        ("Author", "Patrick Quirk"),
        ("Information", "Six independent leaderboards - the 20 processes eating the most CPU, memory, "
                        "swap (commit), disk I/O, GPU and VRAM. UsageMonitor plugin, 1 s refresh."),
        ("Version", "1.0.0"),
        ("License", "Open Source"),
    ))
    out.append(section(
        "Variables",
        ("CpuName", cpu),
        ("Threads", str(threads)),
        ("GpuName", gpu_name),
        ("VramTotal", str(vram_total or 1)),
        ("VramTotalGB", f"{vram_total / GIB:.1f}" if vram_total else "?"),
        ("W", str(width)),
        ("H", str(height)),
        ("Dot", "·"),
        ("GpuTotal", "0"),
        *((f"GpuBar{r}", "0") for r in range(1, ROWS + 1)),
        comment="Hardware facts read at generation time; Gpu* are set live by GpuBoard.lua.",
    ))

    # ---------------------------------------------------------------- styles
    out.append(section(
        "StyleText",
        ("FontFace", "#FontUI#"), ("FontSize", "9"), ("FontColor", "#Text#"),
        ("AntiAlias", "1"),
        comment="-------------------------------------------------------------- styles",
    ))
    out.append(section(
        "StyleName",
        ("W", str(COL_W - VALUE_W)), ("H", "16"), ("ClipString", "1"),
    ))
    out.append(section(
        "StyleValue",
        ("FontFace", "#FontMono#"), ("FontSize", "8"), ("FontColor", "#TextDim#"),
        ("StringAlign", "Right"), ("NumOfDecimals", "1"),
    ))
    out.append(section(
        "StyleRowBar",
        ("BarOrientation", "Horizontal"), ("SolidColor", "#Track#"),
        ("W", str(COL_W)), ("H", "2"),
    ))
    out.append(section(
        "StyleHeadLabel",
        ("FontWeight", "600"), ("FontSize", "8"),
        ("InlineSetting", "CharacterSpacing | 1.4 | 1.4"),
    ))
    out.append(section(
        "StyleHeadCaption",
        ("FontSize", "7"), ("FontColor", "#Faint#"), ("StringAlign", "Right"),
    ))
    out.append(section(
        "StyleHeadBig",
        ("FontWeight", "600"), ("FontSize", "20"), ("NumOfDecimals", "0"),
        ("Text", "%1%"),
        ("InlineSetting", "Size | 11"), ("InlinePattern", "(%)$"),
        ("InlineSetting2", "Color | #TextDim#"), ("InlinePattern2", "(%)$"),
        ("LeftMouseUpAction", '["taskmgr.exe"]'),
        ("ToolTipText", "Open Task Manager"),
    ))
    out.append(section(
        "StyleHeadSub",
        ("FontSize", "8"), ("FontColor", "#TextDim#"), ("StringAlign", "Right"),
        ("NumOfDecimals", "1"),
    ))
    out.append(section(
        "StyleHeadBar",
        ("BarOrientation", "Horizontal"), ("SolidColor", "#Track#"),
        ("W", str(COL_W)), ("H", "3"),
    ))
    out.append(section(
        "StyleRank",
        ("FontFace", "#FontMono#"), ("FontSize", "7"), ("FontColor", "#Faint#"),
        ("StringAlign", "Right"), ("AntiAlias", "1"),
    ))

    # ------------------------------------------------------ system measures
    um = lambda *pairs: (("Measure", "Plugin"), ("Plugin", "UsageMonitor")) + pairs
    calc = lambda formula, *pairs: (("Measure", "Calc"), ("Formula", formula)) + pairs
    out.append(section("MeasureCpuTotal", ("Measure", "CPU"),
                       comment="------------------------------------------------ system totals\n"
                               "; Busy time (% Processor Time) - what the per-process rows add up to."))
    # Task Manager's CPU figure is % Processor Utility = busy time scaled by
    # the effective clock against base clock, so a throttled chip reads lower.
    pi = lambda counter: um(("Category", "Processor Information"), ("Counter", counter),
                            ("Whitelist", "_Total"), ("Index", "1"))
    out.append(section("MeasureCpuUtil", *pi("% Processor Utility")))
    out.append(section("MeasureCpuPerf", *pi("% Processor Performance")))
    out.append(section("MeasureCpuFreq", *pi("Processor Frequency")))
    out.append(section("CalcCpuUtil", *calc("Clamp(MeasureCpuUtil, 0, 100)"),
                       ("RegExpSubstitute", "1"), ("Substitute", '"\\.\\d+$":""')))
    out.append(section("CalcCpuGHz", *calc("MeasureCpuPerf / 100 * MeasureCpuFreq / 1000")))
    for tag, kind in (("Mem", "PhysicalMemory"), ("Swap", "SwapMemory")):
        out.append(section(f"Measure{tag}Used", ("Measure", kind)))
        out.append(section(f"Measure{tag}Total", ("Measure", kind), ("Total", "1")))
        out.append(section(f"Calc{tag}Pct", *calc(f"Clamp(Measure{tag}Used / Max(Measure{tag}Total, 1) * 100, 0, 100)",
                                                  ("MaxValue", "100"))))
        out.append(section(f"Calc{tag}UsedGB", *calc(f"Measure{tag}Used / {GIB}")))
        out.append(section(f"Calc{tag}TotalGB", *calc(f"Measure{tag}Total / {GIB}")))
    out.append(section("MeasureDiskBytes", *um(("Category", "PhysicalDisk"), ("Counter", "Disk Bytes/sec"), ("Index", "0"))))
    out.append(section("CalcDiskBytes", *calc("MeasureDiskBytes")))
    out.append(section("MeasureDiskIdle", *um(("Category", "PhysicalDisk"), ("Counter", "% Idle Time"), ("Index", "-1"))))
    out.append(section("CalcDiskActive", *calc("Clamp(100 - MeasureDiskIdle, 0, 100)", ("MaxValue", "100"))))
    # GPU the way Task Manager counts it. Rollup=0 gives one row per
    # (process, engine) - PIDToName does not work without rollup, so names
    # come from a cached tasklist run by GpuBoard.lua when a new PID shows up.
    for n in range(1, GPU_RAW + 1):
        out.append(section(f"MeasureGpuRaw{n}", *um(("Alias", "GPU"), ("Rollup", "0"), ("PIDToName", "0"), ("Index", str(n))),
                           comment="---- GPU: raw engine rows for GpuBoard.lua" if n == 1 else None))
    out.append(section(
        "MeasureTaskList", ("Measure", "Plugin"), ("Plugin", "RunCommand"),
        ("Parameter", "tasklist /FO CSV /NH"), ("State", "Hide"), ("OutputType", "ANSI"),
        ("FinishAction", '[!CommandMeasure MeasureGpuBoard "OnTaskList()"]'),
    ))
    out.append(section(
        "MeasureGpuBoard", ("Measure", "Script"), ("ScriptFile", "#@#GpuBoard.lua"),
        ("RawCount", str(GPU_RAW)), ("Rows", str(ROWS)),
    ))
    out.append(section("CalcGpuTotal", *calc("#GpuTotal#", ("MaxValue", "100"), ("DynamicVariables", "1"))))
    for r in range(1, ROWS + 1):
        out.append(section(f"CalcGPUBar{r}", *calc(f"#GpuBar{r}#", ("MaxValue", "1"), ("DynamicVariables", "1"))))
    out.append(section("MeasureVramUsed", *um(("Category", "GPU Adapter Memory"), ("Counter", "Dedicated Usage"), ("Index", "0"))))
    out.append(section("CalcVramPct", *calc("Clamp(MeasureVramUsed / #VramTotal# * 100, 0, 100)", ("MaxValue", "100"))))
    out.append(section("CalcVramUsedGB", *calc(f"MeasureVramUsed / {GIB}")))
    out.append(section("MeasureNetIn", ("Measure", "NetIn"), ("Interface", "Best")))
    out.append(section("MeasureNetOut", ("Measure", "NetOut"), ("Interface", "Best")))
    out.append(section("MeasureUptime", ("Measure", "Uptime"), ("Format", "%4!i!d %3!02i!h %2!02i!m")))
    out.append(section("MeasureTime", ("Measure", "Time"), ("Format", "%H:%M:%S")))

    # --------------------------------------------------- per-column rankings
    for key, _label, _cap, _acc, opts, kind in COLUMNS:
        if opts is None:
            continue
        for r in range(1, ROWS + 1):
            m, name, value = f"Measure{key}{r}", f"Meter{key}Name{r}", f"Meter{key}Value{r}"
            out.append(section(
                m, *um(*opts.items(), ("Index", str(r))),
                ("IfCondition", f"{m} < {IDLE[kind]}"),
                ("IfTrueAction", f'[!SetOption {name} FontColor "#Faint#"][!SetOption {value} FontColor "#Faint#"]'),
                ("IfFalseAction", f'[!SetOption {name} FontColor "#Text#"][!SetOption {value} FontColor "#TextDim#"]'),
                ("IfMatch", "^$"),
                ("IfMatchAction", f"[!HideMeter {value}]"),
                ("IfNotMatchAction", f"[!ShowMeter {value}]"),
                comment=f"{key} #{r}" if r == 1 else None,
            ))
            out.append(section(f"Calc{key}{r}", *calc(m)))
            out.append(section(f"Calc{key}Bar{r}", *calc(f"{m} / Max(Measure{key}1, 0.000001)", ("MaxValue", "1"))))

    # ---------------------------------------------------------------- meters
    out.append(section(
        "MeterBackground", ("Meter", "Shape"),
        ("Shape", "Rectangle 0.5,0.5,(#W#-1),(#H#-1),14 | Fill Color #Bg# | StrokeWidth 1 | Stroke Color #Border#"),
        comment="---------------------------------------------------------------- meters",
    ))
    out.append(section(
        "MeterTitle", ("Meter", "String"), ("MeterStyle", "StyleText"),
        ("X", str(PAD)), ("Y", str(TITLE_Y)),
        ("FontWeight", "600"), ("FontSize", "14"), ("Text", "Top 20 // Processes"),
        ("InlineSetting", "Color | #Cpu#"), ("InlinePattern", "(//)"),
        ("InlineSetting2", "Color | #TextDim#"), ("InlinePattern2", "(Processes)"),
        ("InlineSetting3", "Weight | 400"), ("InlinePattern3", "(Processes)"),
        ("LeftMouseUpAction", '["taskmgr.exe"]'), ("ToolTipText", "Open Task Manager"),
    ))
    out.append(section(
        "MeterMeta", ("Meter", "String"), ("MeterStyle", "StyleText"),
        ("MeasureName", "MeasureNetIn"), ("MeasureName2", "MeasureNetOut"),
        ("MeasureName3", "MeasureUptime"), ("MeasureName4", "MeasureTime"),
        ("X", str(right)), ("Y", str(TITLE_Y + 5)), ("StringAlign", "Right"),
        ("FontFace", "#FontMono#"), ("FontSize", "8"), ("FontColor", "#TextDim#"),
        ("AutoScale", "1"), ("NumOfDecimals", "1"),
        ("Text", "#CpuName# · #Threads#T · #GpuName#      NET ↓ %1B/s  ↑ %2B/s      UP %3      %4"),
        ("InlineSetting", "Color | #Faint#"), ("InlinePattern", "(NET|UP|↓|↑)"),
    ))
    out.append(section(
        "MeterRule", ("Meter", "Image"), ("SolidColor", "#Hairline#"),
        ("X", str(PAD)), ("Y", str(RULE_Y)), ("W", str(width - 2 * PAD)), ("H", "1"),
    ))

    heads = {
        "CPU": ("MeasureCpuTotal", (("MeasureName", "CalcCpuUtil"), ("MeasureName2", "CalcCpuGHz"),
                                    ("Text", "%1% util · %2 GHz"),
                                    ("ToolTipText", "Task Manager shows utility: busy time x effective clock / base clock"))),
        "RAM": ("CalcMemPct", (("MeasureName", "CalcMemUsedGB"), ("MeasureName2", "CalcMemTotalGB"),
                               ("Text", "%1 / %2 GB"))),
        "SWAP": ("CalcSwapPct", (("MeasureName", "CalcSwapUsedGB"), ("MeasureName2", "CalcSwapTotalGB"),
                                 ("Text", "%1 / %2 GB"))),
        "DISK": ("CalcDiskActive", (("MeasureName", "CalcDiskBytes"), ("AutoScale", "1"),
                                    ("Text", "%1B/s"))),
        "GPU": ("CalcGpuTotal", (("Text", "#GpuName#"),)),
        "VRAM": ("CalcVramPct", (("MeasureName", "CalcVramUsedGB"), ("Text", "%1 / #VramTotalGB# GB"))),
    }

    for i, (key, label, caption, acc, _opts, kind) in enumerate(COLUMNS):
        x = col_x(i)
        xr = x + COL_W
        big, sub = heads[key]
        out.append(section(
            f"Meter{key}Label", ("Meter", "String"), ("MeterStyle", "StyleText | StyleHeadLabel"),
            ("X", str(x)), ("Y", str(HEAD_Y)), ("FontColor", f"#{acc}#"), ("Text", label),
            comment=f"---- {label} column",
        ))
        out.append(section(
            f"Meter{key}Caption", ("Meter", "String"), ("MeterStyle", "StyleText | StyleHeadCaption"),
            ("X", str(xr)), ("Y", str(HEAD_Y + 1)), ("Text", caption),
        ))
        out.append(section(
            f"Meter{key}Big", ("Meter", "String"), ("MeterStyle", "StyleText | StyleHeadBig"),
            ("MeasureName", big), ("X", str(x - 1)), ("Y", str(HEAD_Y + 13)),
        ))
        out.append(section(
            f"Meter{key}Sub", ("Meter", "String"), ("MeterStyle", "StyleText | StyleHeadSub"),
            ("X", str(xr)), ("Y", str(HEAD_Y + 27)), ("W", str(COL_W - 74)), ("ClipString", "1"),
            *sub,
        ))
        out.append(section(
            f"Meter{key}HeadBar", ("Meter", "Bar"), ("MeterStyle", "StyleHeadBar"),
            ("MeasureName", big), ("BarColor", f"#{acc}#"),
            ("X", str(x)), ("Y", str(HEAD_Y + 50)),
        ))
        fmt = {"pct": "%1%", "bytes": "%1B", "rate": "%1B/s"}[kind]
        scripted = _opts is None
        for r in range(1, ROWS + 1):
            y = LIST_Y + (r - 1) * ROW_H
            name_pairs = [("Meter", "String"), ("MeterStyle", "StyleText | StyleName"),
                          ("X", str(x)), ("Y", str(y))]
            if scripted:
                # GpuBoard.lua sets Text to "name · engine"; the engine reads faint.
                name_pairs += [("Text", ""), ("InlineSetting", "Color | #Faint#"),
                               ("InlinePattern", " · .*$")]
            else:
                name_pairs.append(("MeasureName", f"Measure{key}{r}"))
            if r == 1:
                name_pairs.append(("FontWeight", "600"))
            out.append(section(f"Meter{key}Name{r}", *name_pairs))
            val_pairs = [("Meter", "String"), ("MeterStyle", "StyleText | StyleValue"),
                         ("X", str(xr)), ("Y", str(y + 2))]
            if scripted:
                val_pairs.append(("Text", ""))
            else:
                val_pairs += [("MeasureName", f"Calc{key}{r}"), ("Text", fmt)]
            if kind != "pct":
                val_pairs.append(("AutoScale", "1"))
            out.append(section(f"Meter{key}Value{r}", *val_pairs))
            out.append(section(
                f"Meter{key}Bar{r}", ("Meter", "Bar"), ("MeterStyle", "StyleRowBar"),
                ("MeasureName", f"Calc{key}Bar{r}"), ("BarColor", f"#{acc}#"),
                ("X", str(x)), ("Y", str(y + 17)),
            ))

    for r in range(1, ROWS + 1):
        out.append(section(
            f"MeterRank{r}", ("Meter", "String"), ("MeterStyle", "StyleRank"),
            ("X", str(PAD + 16)), ("Y", str(LIST_Y + (r - 1) * ROW_H + 3)), ("Text", f"{r:02d}"),
            comment="---- rank gutter" if r == 1 else None,
        ))

    out.append(section(
        "MeterFootLeft", ("Meter", "String"), ("MeterStyle", "StyleText"),
        ("X", str(PAD)), ("Y", str(foot_y)), ("FontSize", "7"), ("FontColor", "#Faint#"),
        ("Text", "Each column ranked on its own  ·  bars relative to #1  ·  faint = idle"),
        comment="---- footer",
    ))
    out.append(section(
        "MeterFootRight", ("Meter", "String"), ("MeterStyle", "StyleText"),
        ("X", str(right)), ("Y", str(foot_y)), ("FontSize", "7"), ("FontColor", "#Faint#"),
        ("StringAlign", "Right"),
        ("Text", "UsageMonitor  ·  1 s  ·  click a total for Task Manager"),
    ))

    text = "\n".join(out)
    # UTF-16 LE with BOM: Rainmeter's encoding for skins with non-ASCII text.
    OUT.write_text(text, encoding="utf-16", newline="\r\n")
    print(f"wrote {OUT} ({width}x{height}, {len(COLUMNS)} columns x {ROWS} rows)")
    print(f"cpu={cpu!r} threads={threads} gpu={gpu_name!r} vram={vram_total / GIB:.1f} GiB")


if __name__ == "__main__":
    main()
