[Rainmeter]
Update=500
Author= -HipHopium-
DynamicVariables=1

[Variables]
@include=#@#Variables.inc
@include2=#@#Language\#Language#.inc

[Style]
FontColor=#FontColor1#
FontFace=#FontFace#
AntiAlias=1

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterLine]
Meter=IMAGE
X=0
Y=150
W=450
H=1
SolidColor=255,255,255
Group=Current

;-------------------------------------------------------------
;-------------------------------------------------------------

[mCurrent]
Measure=Plugin
Plugin=Plugins\WebParser.dll
UpdateRate=1800
Url=http://wxdata.weather.com/weather/local/#Location#?cc=*&unit=#Unit#&dayf=1
RegExp="(?siU).*<locale>(.*)</locale>.*<ut>(.*)</ut>.*<ud>(.*)</ud>.*<us>(.*)</us>.*<up>(.*)</up>.*<ur>(.*)</ur>.*<loc id="(.*)">.*<dnam>(.*)</dnam>.*<tm>(.*)</tm>.*<lat>(.*)</lat>.*<lon>(.*)</lon>.*<sunr>(.*)</sunr>.*<suns>(.*)</suns>.*<zone>(.*)</zone>.*<cc>.*<lsup>(.*)</lsup>.*<obst>(.*)</obst>.*<tmp>(.*)</tmp>.*<flik>(.*)</flik>.*<t>(.*)</t>.*<icon>(.*)</icon>.*<bar>.*<r>(.*)</r>.*<d>(.*)</d>.*<wind>.*<s>(.*)</s>.*<gust>(.*)</gust>.*<d>(.*)</d>.*<t>(.*)</t>.*<hmid>(.*)</hmid>.*<vis>(.*)</vis>.*<uv>.*<i>(.*)</i>.*<t>(.*)</t>.*<dewp>(.*)</dewp>.*<moon>.*<icon>(.*)</icon>.*<t>(.*)</t>.*<ppcp>(.*)</ppcp>.*"
StringIndex=1

[mToday]
Measure=Plugin
Plugin=Plugins\WebParser.dll
UpdateRate=1800
Url=http://wxdata.weather.com/weather/local/#Location#?cc=*&unit=#Unit#&dayf=1
RegExp="(?siU)<dayf>.*<lsup>(.*)</lsup>.*<day d="0" t="(.*)" dt="(.*)".*<hi>(.*)</hi>.*<low>(.*)</low>.*<sunr>(.*)</sunr>.*<suns>(.*)</suns>(?(?=.*<part p="d">).*<icon>(.*)</icon>.*<t>(.*)</t>.*<wind>.*(.*).*<gust>(.*)</gust>.*<d>(.*)</d>.*<t>(.*)</t>.*<bt>(.*)</bt>.*<ppcp>(.*)</ppcp>.*<hmid>(.*)</hmid>).*<part p="n">.*<icon>(.*)</icon>.*<t>(.*)</t>.*<wind>.*(.*).*<gust>(.*)</gust>.*<d>(.*)</d>.*<t>(.*)</t>.*<bt>(.*)</bt>.*<ppcp>(.*)</ppcp>.*<hmid>(.*)</hmid>.*"
StringIndex=1

;-------------------------------------------------------------
;-------------------------------------------------------------

[mIconCurrent]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[mCurrent]
StringIndex=20

[mTempCurrent]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[mCurrent]
StringIndex=17

[mConditionsCurrent]
Measure=Plugin
Plugin=Plugins\WebParser.dll
Url=[mCurrent]
StringIndex=19
Substitute=#Conditions#

[mLowTemp]
Measure=Plugin
Group=Weather
Plugin=WebParser
URL=[mToday]
StringIndex=5
Disabled=1

[mHighTemp]
Measure=Plugin
Group=Weather
Plugin=WebParser
URL=[mToday]
StringIndex=4
Disabled=1

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterCurrentIcon]
MeasureName=mIconCurrent
Meter=Image
ImagePath=#@#WeatherIcons
PreserveAspectRatio=1
X=170
Y=0
W=120
Group=Current

[MeterTempCurrent]
MeasureName=mTempCurrent
Meter=String
MeterStyle=Style
X=70
Y=70
FontColor=#FontColor2#
FontSize=48
StringAlign=Center
Text="%1°"
Group=Current

[MeterConditionsCurrent]
MeasureName=mConditionsCurrent
Meter=String
MeterStyle=Style
X=225
Y=165
W=440
H=40
FontColor=#FontColor2#
FontSize=20
StringAlign=Center
ClipString=1
Group=Current

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterLow]
Meter=String
MeasureName=mLowTemp
Meter=String
MeterStyle=Style
X=115
Y=115
FontSize=14
Text=%1°
Group=Current
Prefix="#Low#: "

[MeterHigh]
Meter=String
MeasureName=mHighTemp
Meter=String
MeterStyle=Style
X=255
Y=115
FontSize=14
Text=%1°
Group=Current
Prefix="#High#: "

;-------------------------------------------------------------
;-------------------------------------------------------------

[Background]
Meter=Image
ImageName=#@#SettingsBg.png
X=40
Y=20
W=380
H=250
Hidden=1
Group=Settings
AntiAlias=1

[SettingsIconBackground]
Meter=IMAGE
SolidColor=0,0,0,1
X=0
Y=0
W=460
H=200
MouseOverAction=[!ShowMeter "SettingsIcon"] 
MouseLeaveAction=[!HideMeter "SettingsIcon"]
Group=Current

[SettingsIcon]
Meter=Image
ImageName=#@#Settings.png
X=410
Y=60
W=25
ToolTipText=Settings.
LeftMouseUpAction=[!WriteKeyValue Variables Hidden "0" "#@#Variables.inc"][!HideMeterGroup Current][!ShowMeterGroup Settings][!Redraw]
AntiAlias=1
Hidden=1
Group=Current

[WeatherCode]
Meter=String
StringAlign=Left
FontColor=255,255,255
FontFace=Segoe UI Light
FontSize=14
X=40
Y=80
Text=Enter Location Code Here ->
Hidden=1
AntiAlias=1
Group=Settings

[MeterCode]
Meter=String
StringAlign=Center
FontFace=Segoe UI Light
FontColor=0,174,239
FontSize=15
X=310r
Y=0r
Text=#Location#
AntiAlias=1
Hidden=1
Group=Settings
AntiAlias=1
ToolTipText=Type your weather "Location Code" and press the "Enter" key to Apply changes.
LeftMouseUpAction=[!PluginBang "meterInput ExecuteBatch 1"]

[MeterInput]
Measure=Plugin
Plugin=InputText.dll
X=300
Y=84
W=110
H=20
Hidden=1
Group=Settings
StringAlign=Left
FontFace=Segoe UI Light
AntiAlias=1
FontSize=14
FocusDismiss=1
Command1=[!WriteKeyValue Variables Location "$UserInput$""#@#Variables.inc"][!Refresh *] 
DefaultValue="#Location#"

[LocationFind]
Meter=String
StringAlign=Left
FontFace=Segoe UI Light
FontColor=255,255,255
FontSize=14
X=40
Y=50
Text=Find Your Code Here -> 
Hidden=1
AntiAlias=1
Group=Settings

[LocationCode]
Meter=Image
ImageName=#@#Location.png
X=265r
Y=-8r
W=44
AntiAlias=1
Hidden=1
Group=Settings
ToolTipText="Find your weather "Location Code" on this site."
LeftMouseDownAction=["https://weather.codes/"]

[weatherLang]
Meter=String
StringAlign=Left
FontFace=Segoe UI Light
FontColor=255,255,255
FontSize=15
X=40
Y=110
Text=Enter Language Here -> 
AntiAlias=1
Hidden=1
Group=Settings

[meterCode2]
Meter=String
StringAlign=Center
FontColor=0,174,239
FontSize=15
X=300r
Y=5r
Text=#Language#
AntiAlias=1
Hidden=1
Group=Settings
AntiAlias=1
ToolTipText=Type your "Language" and press the "Enter" key to Apply changes.#CRLF#Suported languages for now:Czech,English,French,German,Greek,#CRLF#Italian,Polish,Russian,Serbian,Spanish,Turkish,Portuguese.
LeftMouseUpAction=[!PluginBang "meterInput2 ExecuteBatch 1"]

[meterInput2]
Measure=Plugin
Plugin=InputText.dll
X=300
Y=115
W=110
H=22
Hidden=13
Group=Settings
StringAlign=Left
FontSize=14
FocusDismiss=1
AntiAlias=1
Command1=[!WriteKeyValue Variables Language "$UserInput$""#@#Variables.inc"][!Refresh *] 
DefaultValue="#Language#"

[Celsius]
Meter=Image
ImageName=#@#Celsius.png
X=80
Y=180
W=95
Hidden=1
Group=Settings
LeftMouseUpAction=[!WriteKeyValue Variables Unit "m" "#@#Variables.inc"][!Refresh]

[Fahrenheit]
Meter=Image
ImageName=#@#Fahrenheit.png
X=280
Y=180
W=95
Hidden=1
Group=Settings
LeftMouseUpAction=[!WriteKeyValue Variables Unit "f" "#@#Variables.inc"][!Refresh][!HideMeter Fahrenheit]

[Close]
Meter=Image
ImageName=#@#Close.png
X=180
Y=220
W=95
PreserveAspectRatio=1
Hidden=1
Group=Settings
LeftMouseUpAction=[!ShowMeterGroup Current][!HideMeterGroup Settings][!Redraw]

[Instruction]
Meter=String
MeterStyle=Style
FontFace=Segoe UI Light
FontColor=255,255,255
FontSize=15
X=40
Y=140
Text=Translate Instruction -> 
Hidden=1
Group=Settings

[BookImage]
Meter=IMAGE
ImageName=#@#Book.png
PreserveAspectRatio=1
X=265r
Y=r
W=26
Group=Settings
Hidden=1
ToolTipText="Click here to see,how to translate to your language"
LeftMouseUpAction=!Execute ["#ROOTCONFIGPATH#@Resources\Language\YourLanguage.inc"]
