[Rainmeter]
Author=achfighter
Update=2000
LeftMouseDoubleClickAction=!RainmeterDeactivateConfig

[Metadata]
Name=CPUgauge
Information=Graphical indicator for CPU Usage
License=Free for Personal Use in Creative Common, Not Allowed Commerical Use! If you are using this widget, you agree to "License" agreement. 
Version=v0.3

[Variables]
FontName=Segoe WP Semibold
FontColor=90,90,90,225
FontSize=13
Image=#CURRENTPATH#cpubackground.png
Image=#CURRENTPATH#cpurotator.png

[MeasureCPU]
Measure=CPU

;[MeasureCPULoad]
Measure=Plugin
Plugin=Plugins\CoreTemp.dll
CoreTempType=Load
MaxValue=100
MinValue=0

[MeasureCPUFreq]
Measure=Plugin
Plugin=PowerPlugin.dll
PowerState=MHZ

[MeasureAngle]
Measure=CPU
; (percentages - 1) * (1 / 100)
Formula=(MeasureCPU % 360) * 0,001
Disabled=#percentages#

[MeasureArc]
; Measures the size of used RAM.
Measure=CPU
; 0 + 1 / 100
Formula=(MeasureCPU % 360) * 0,001
UpdateDivider=-1

[MeasureRotator]
Measure=CPU
; 0 + 1 / 100
Formula=(MeasureArc % 360) * 0,001
UpdateDivider=-1

[TextCPU]
Text="CPU"
Meter=STRING
X=70
Y=35
FontFace=#FontName#
FontColor=#FontColor#
FontSize=#FontSize#
StringEffect=Shadow
FontEffectColor=0,0,0,90
AntiAlias=1



[MeterCPUFreq]
MeasureName=MeasureCPUFreq
Meter=STRING
X=50
Y=115
FontFace=#FontName#
FontColor=#FontColor#
FontSize=#FontSize#
AntiAlias=1
StringEffect=Shadow
FontEffectColor=0,0,0,90
PostFix=" Mhz"

[MeterCPULoad]
MeasureName=MeasureCPU
Meter=STRING
X=40
Y=45
FontFace=#FontName#
FontColor=#FontColor#
FontSize=40
AntiAlias=1
StringEffect=Shadow
FontEffectColor=0,0,0,90
PostFix="%"
Percentual=1

[Background Meter]
Meter=Image
ImageName=cpubackground
X=0
Y=0
W=180
H=180

[MeterCPUArc]
MeasureName=MeasureCPU
Meter=ROUNDLINE
W=180
H=180
LineStart=67
LineLength=81
LineColor=90,90,90,240
; 1 / 100 
StartAngle=(4 / 1 % 360) + 0.7
AntiAlias=1
Solid=1
DynamicVariables=1
UpdateDivider=1

[MeterCPURotator]
Meter=ROTATOR
MeasureName=MeasureCPU
ImageName=cpurotator
X=0
Y=0
W=180
H=180
OffsetX=90
OffsetY=90
StartAngle=(4 % 360) + 2.2667
RotationAngle=6.2832
UpdateDivider=1


